skyscrapper/skyscrapper/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.landing_page, name="landing_page"),
    url(r'^tracker/', include('tracker.urls')),
    url(r'^takemehome/', include('takemehome.urls')),
    url(r'^admin/', admin.site.urls),
]

skyscrapper/tracker/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^trip/(?P<pk>[0-9]+)/$', views.trip_detail, name='trip_detail'),
    url(r'^trip/new/$', views.trip_new, name='trip_new'),
]

skyscrapper/tracker/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone


LOCALS = (
    ('LCG','A Coruña'),
    ('AAL','Aalborg'),
    ('ACC','Acra'),
    ('ALC','Alicante'),
    ('LEI','Almería'),
    ('AMS','Ámsterdam'),
    ('ALG','Argel'),
    ('OVD','Asturias (Oviedo)'),
    ('ATH','Atenas'),
    ('BJL','Banjul'),
    ('BCN','Barcelona'),
    ('BRI','Bari'),
    ('BSL','Basilea'),
    ('BIA','Bastia (Córcega)'),
    ('BEY','Beirut'),
    ('BEG','Belgrado'),
    ('BGO','Bergen'),
    ('TXL','Berlín (Tegel)'),
    ('BIO','Bilbao'),
    ('BHX','Birmingham'),
    ('BLQ','Bolonia'),
    ('BES','Brest'),
    ('BDS','Bríndisi'),
    ('BRU','Bruselas'),
    ('OTP','Bucarest'),
    ('BUD','Budapest'),
    ('BOD','Burdeos'),
    ('CAG','Cagliari'),
    ('CWL','Cardiff'),
    ('CMN','Casablanca'),
    ('CTA','Catania'),
    ('EFL','Cefalonia'),
    ('CLJ','Cluj-Napoca'),
    ('CPH','Copenhague'),
    ('CFU','Corfú'),
    ('KRK','Cracovia'),
    ('HER','Creta'),
    ('DKR','Dakar'),
    ('DUB','Dublín'),
    ('DBV','Dubrovnik'),
    ('DUS','Düsseldorf'),
    ('EDI','Edimburgo'),
    ('EIN','Eindhoven'),
    ('ARN','Estocolmo'),
    ('FAO','Faro'),
    ('FEZ','Fez'),
    ('FLR','Florencia'),
    ('FRA','Frankfurt'),
    ('FUE','Fuerteventura'),
    ('GOA','Génova'),
    ('GVA','Ginebra'),
    ('GOT','Gotemburgo'),
    ('LPA','Gran Canaria'),
    ('GRX','Granada'),
    ('HAM','Hamburgo'),
    ('HAJ','Hanóver'),
    ('HEL','Helsinki'),
    ('IBZ','Ibiza'),
    ('XRY','Jerez (Cádiz)'),
    ('KGD','Kaliningrado'),
    ('AOK','Kárpatos'),
    ('IEV','Kiev'),
    ('KGS','Kos'),
    ('SPC','La Palma'),
    ('LMP','Lampedusa'),
    ('ACE','Lanzarote'),
    ('LCA','Lárnaca'),
    ('LBA','Leeds'),
    ('LIL','Lille'),
    ('LIS','Lisboa'),
    ('LGW','Londres'),
    ('LHR','Londres (Heathrow)'),
    ('LTN','Londres (Luton)'),
    ('LUX','Luxemburgo'),
    ('LYS','Lyon'),
    ('FNC','Madeira'),
    ('MAD','Madrid'),
    ('AGP','Málaga'),
    ('PMI','Mallorca'),
    ('MLA','Malta'),
    ('MAN','Manchester'),
    ('RAK','Marrakech'),
    ('MRS','Marsella'),
    ('MAH','Menorca'),
    ('JMK','Mikonos'),
    ('MXP','Milán'),
    ('MSQ','Minsk'),
    ('DME','Moscú'),
    ('MUC','Múnich'),
    ('NDR','Nador'),
    ('NTE','Nantes'),
    ('NAP','Nápoles'),
    ('NCL','Newcastle'),
    ('NCE','Niza'),
    ('NUE','Nuremberg'),
    ('OLB','Olbia'),
    ('OPO','Oporto'),
    ('ORN','Orán'),
    ('OSL','Oslo'),
    ('PMO','Palermo'),
    ('CDG','París'),
    ('ORY','París (Orly)'),
    ('PSA','Pisa (Toscana)'),
    ('PRG','Praga'),
    ('PVK','Préveza'),
    ('KEF','Reikiavik'),
    ('RNS','Rennes'),
    ('RHO','Rodas'),
    ('FCO','Roma (Fiumicino)'),
    ('RTM','Róterdam'),
    ('LED','San Petersburgo'),
    ('EAS','San Sebastián'),
    ('SDR','Santander'),
    ('SCQ','Santiago'),
    ('JTR','Santorini'),
    ('SVQ','Sevilla'),
    ('SPU','Split'),
    ('STR','Stuttgart'),
    ('TLL','Tallin'),
    ('TNG','Tánger'),
    ('TLV','Tel Aviv'),
    ('TFN','Tenerife'),
    ('TFS','Tenerife Sur'),
    ('SKG','Tesalónica'),
    ('TLS','Toulouse'),
    ('TUN','Túnez'),
    ('TRN','Turin'),
    ('VLC','Valencia'),
    ('VLL','Valladolid'),
    ('WAW','Varsovia'),
    ('VCE','Venecia'),
    ('VRN','Verona'),
    ('VIE','Viena'),
    ('VGO','Vigo'),
    ('ZAD','Zadar'),
    ('ZAG','Zagreb'),
    ('ZTH','Zante'),
    ('ZAZ','Zaragoza'),
    ('ZRH','Zúrich'),
)

class Trip(models.Model):
    origin = models.CharField(max_length=3, choices=LOCALS)
    destination = models.CharField(max_length=3, choices=LOCALS)
    date_departure = models.DateField()
    date_return = models.DateField()
    activated = models.BooleanField(default=True)
    one_way = models.BooleanField(default=False)
    published_date = models.DateTimeField(auto_now_add = True)
    def __str__(self):
        return "{}-{} {}/{}".format(self.origin,self.destination,self.date_departure,self.date_return)

class TimeSeries(models.Model):
    trip = models.ForeignKey(Trip, related_name="timeseries")
    time = models.DateTimeField()
    origin = models.CharField(max_length=3)
    destination = models.CharField(max_length=3)
    isreturn = models.BooleanField(default=False)
    flightname = models.CharField(max_length=20, default="NA")
    def __str__(self):
        return "{}-{} {} parent:{}".format(self.origin,self.destination,self.time, self.trip)

class PricePoint(models.Model):
    timestamp = models.DateTimeField(default=timezone.now)
    price = models.DecimalField(max_digits=10, decimal_places=5)
    timeseries = models.ForeignKey(TimeSeries, related_name="pricepoints")
    class Meta:
        ordering = ['timestamp']
    def __str__(self):
        return "{} {} parent:{}".format(self.timestamp,self.price,self.timeseries)

skyscrapper/tracker/forms.py
from django import forms
from .models import Trip
from django.contrib.admin import widgets

class TripForm(forms.ModelForm):
    class Meta:
        model = Trip
        fields = ['origin', 'destination', 'date_departure', 'date_return', 'one_way']

skyscrapper/tracker/views.py
from django.http import HttpResponse, HttpResponseRedirect
from tracker.forms import TripForm
from django.shortcuts import render, redirect
from tracker.models import Trip, TimeSeries, PricePoint
from skyscrapper.views import vueling_track_round_trip
import datetime
import pytz

def trip_new(request):
    if request.method == "POST":
        form = TripForm(request.POST)
        if form.is_valid():
            trip = form.save(commit=False)
            trip.save()
            res = vueling_track_round_trip(trip)
            for flight in res["departure"]:
                price = flight[0]
                hour = int(flight[1][:2])
                minute = int(flight[1][3:5])
                time = datetime.datetime(trip.date_departure.year, trip.date_departure.month, trip.date_departure.day, hour, minute, tzinfo=pytz.UTC)
                flightname = str(time.hour)+":"+str(time.minute)+trip.origin
                ts = TimeSeries(trip=trip, time=time, origin=trip.origin, destination=trip.destination, flightname=flightname)
                ts.save()
                pp = PricePoint(price=price, timeseries=ts)
                pp.save()
            if not (trip.one_way):
                for flight in res["return"]:
                    price = flight[0]
                    hour = int(flight[1][:2])
                    minute = int(flight[1][3:5])
                    time = datetime.datetime(trip.date_departure.year, trip.date_departure.month, trip.date_departure.day, hour, minute, tzinfo=pytz.UTC)
                    flightname = str(time.hour)+":"+str(time.minute)+trip.destination
                    ts = TimeSeries(trip=trip, time=time, origin=trip.destination, destination=trip.origin, isreturn=True, flightname=flightname)
                    ts.save()
                    pp = PricePoint(price=price, timeseries=ts)
                    pp.save()
            return HttpResponseRedirect('/')
    else:
        form = TripForm()
    return render(request, 'tracker/trip_edit.html', {'form': form})



def trip_detail(request, pk):
    trip = Trip.objects.get(pk=pk)
    timeseries = trip.timeseries.all()
    res = {}
    res["departure"] = {}
    res["return"] = {}
    res["return"]['flightnames']=[]
    res["departure"]['flightnames']=[]
    for ts in timeseries:
        flightname = ts.flightname
        pricepoints = ts.pricepoints.all()
        if (ts.isreturn):
            res["return"]['flightnames'].append(flightname)
            if not "values" in res["return"]:
                res["return"]["values"]=[["new Date({},{},{},{},{})".format(pp.timestamp.year,pp.timestamp.month,pp.timestamp.day,pp.timestamp.hour,pp.timestamp.minute)] for pp in pricepoints]
            for i,pp in enumerate(pricepoints):
                res["return"]["values"][i].append(pp.price)
        else:
            res["departure"]['flightnames'].append(flightname)
            if not "values" in res["departure"]:
                res["departure"]["values"]=[["new Date({},{},{},{},{})".format(pp.timestamp.year,pp.timestamp.month,pp.timestamp.day,pp.timestamp.hour,pp.timestamp.minute)] for pp in pricepoints]
            for i,pp in enumerate(pricepoints):
                res["departure"]["values"][i].append(pp.price)
    #print(res)
    return render(request, 'tracker/trip_detail.html', {'flights':res, 'trip':trip})

skyscrapper/tracker/templates/tracker/trip_detail.html
{% extends 'base.html' %}

{% block content %}
    <script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
    <div>
        <h3>{{ trip.get_origin_display }}-{{ trip.get_destination_display }} {{ trip.date_departure }}{% if not trip.one_way %}/{{ trip.date_return }}{% endif %}</h3>
        <h4>Departure/s</h4>
         <div id="chart_departures"></div>
        {% if not flights.departure.flightnames %}<p>No flights found</p>{% endif %}

        {% if not trip.one_way %}
            <h4>Return/s</h4>
            <div id="chart_returns"></div>
            {% if not flights.return.flightnames %}<p>No flights found</p>{% endif %}
        {% endif %}

    </div>

<script>



google.charts.load('current', {packages: ['corechart', 'line']});
google.charts.setOnLoadCallback(drawDepartures);

{% if not trip.one_way %}{% if flights.departure %}
google.charts.setOnLoadCallback(drawReturns);
{% endif %}{% endif %}

function drawDepartures() {
      var data = new google.visualization.DataTable();
      data.addColumn('date', 'Date');
      {% for dep in flights.departure.flightnames %}
        data.addColumn('number', '{{ dep }}');
      {% endfor %}

      data.addRows([
      {% for timearray in flights.departure.values %}

        [{% for val in timearray %}
            {{ val }},
        {% endfor %}],
      {% endfor %}
        ])

      var options = {
        hAxis: {
          gridlines: {
            count: -1,
            units: {
              days: {format: ['MMM dd']},
              hours: {format: ['HH:mm', 'ha']},
            }
          },
          minorGridlines: {
            units: {
              hours: {format: ['hh:mm:ss a', 'ha']},
              minutes: {format: ['HH:mm a Z', ':mm']}
            }
          }
        },

        vAxis: {
          title: 'Price evolution (Euros)'
        },
        series: {
          1: {curveType: 'function'}
        },
        height: 350,
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_departures'));
      chart.draw(data, options);
    }

{% if not trip.one_way %}{% if flights.return %}
function drawReturns() {
      var data = new google.visualization.DataTable();
      data.addColumn('date', 'Date');
      {% for dep in flights.return.flightnames %}
        data.addColumn('number', '{{ dep }}');
      {% endfor %}

      data.addRows([
      {% for timearray in flights.return.values %}

        [{% for val in timearray %}
            {{ val }},
        {% endfor %}],
      {% endfor %}
        ])


      var options = {
        hAxis: {
          gridlines: {
            count: -1,
            units: {
              days: {format: ['MMM dd']},
              hours: {format: ['HH:mm', 'ha']},
            }
          },
          minorGridlines: {
            units: {
              hours: {format: ['hh:mm:ss a', 'ha']},
              minutes: {format: ['HH:mm a Z', ':mm']}
            }
          }
        },

        vAxis: {
          title: 'Price evolution (Euros)'
        },
        series: {
          1: {curveType: 'function'}
        },
        height: 350,
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart_returns'));
      chart.draw(data, options);
    }
{% endif %}{% endif %}
</script>
{% endblock %}

skyscrapper/tracker/templates/tracker/trip_edit.html
{% extends 'base.html' %}

{% block content %}
    <h2>New trip for price variation analysis</h2>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>

    <script>
        $("#id_one_way").change(function() {
            $("#id_date_return").toggle();
            $("#id_date_return").parent().find("label").toggle();
            if ($("#id_date_return").css("display") == "none"){
                $("#id_date_return").val("01/01/2017");
            } else {
                $("#id_date_return").val("");
            }
        });
    </script>
    <script>
      $(function() {
        $( "#id_date_departure" ).datepicker();
        $( "#id_date_return" ).datepicker();
      });
    </script>
{% endblock %}